# Generated by Django 3.2.8 on 2021-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookpage',
            field=models.FileField(upload_to='files/bookpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(upload_to='files/coverpage/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(upload_to='files/category/'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='pic',
            field=models.FileField(upload_to='files/writer/'),
        ),
    ]
