# Generated by Django 3.2.8 on 2021-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_review_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_star',
            field=models.IntegerField(default=0),
        ),
    ]
