# Generated by Django 3.2.8 on 2021-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_review_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='totalrating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
