# Generated by Django 3.2.9 on 2021-11-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='book',
        ),
    ]
